# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShapeUpDownloader < Formula
  desc "Download and convert Basecamp's Shape Up book for e-readers"
  homepage "https://github.com/benjaminkitt/shape-up-downloader"
  version "1.0.4"

  on_macos do
    on_intel do
      url "https://github.com/benjaminkitt/shape-up-downloader/releases/download/v1.0.4/shape-up-downloader_Darwin_x86_64.tar.gz"
      sha256 "948ed50832c9c9d57ac71afd76ea11af8d38a026cb96fcf4143e950bbc6ddabf"

      def install
        bin.install "shape-up"
      end
    end
    on_arm do
      url "https://github.com/benjaminkitt/shape-up-downloader/releases/download/v1.0.4/shape-up-downloader_Darwin_arm64.tar.gz"
      sha256 "2d37216d7c6bd81707a6bcfc9cea4922fdca31cf467cff7469c9dc50c2cf4da0"

      def install
        bin.install "shape-up"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/benjaminkitt/shape-up-downloader/releases/download/v1.0.4/shape-up-downloader_Linux_x86_64.tar.gz"
        sha256 "0e090690ff732d7f1599d0f7d8fdc7ef1ea5426b23e3d7196ecb48483885c326"

        def install
          bin.install "shape-up"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/benjaminkitt/shape-up-downloader/releases/download/v1.0.4/shape-up-downloader_Linux_arm64.tar.gz"
        sha256 "4b82327b427656badfeb9d2e3533e0e44fb9487bdca08de46576a2fe88b6b493"

        def install
          bin.install "shape-up"
        end
      end
    end
  end
end
